services:
  moritzsoft-search:
    build:
      context: .
      dockerfile: Dockerfile
    image: moritzsoft-search:latest
    ports:
      - "8855:8855"
    restart: unless-stopped

networks:
  default:
    name: moritzsoft-search-network
